version: 0.2
env:
  variables:
    IMAGE_REPO_NAME: aitraineree
    IMAGE_TAG: latest
    SAGEMAKER_ACCOUNT: 763104351884

phases:
  pre_build:
    commands:
      - set -e  # Verbose output
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --output text --query Account)
      - echo "We're at $AWS_ACCOUNT_ID"
      - pip install --upgrade pip
      - pip uninstall -qy awscli
      - curl -s "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip && unzip -oq /tmp/awscliv2.zip -d /tmp && /tmp/aws/install
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin $SAGEMAKER_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com
  build:
    commands:
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

